include:
  - docker-compose.common.yml

version: "3"
services:
  vathmos_backend:
     build:
       context: .
       dockerfile: Dockerfile
     image: vathmos_backend
     container_name: vathmos_backend
     ports:
       - "${PORT}:${PORT}"
     networks:
       - vathmos_backend
     command: npm run start:dev
     env_file:
       - .env