version: "3"
services:
  database:
    container_name: ${MYSQL_HOST}
    image: mysql:8.0.34
    restart: unless-stopped
    env_file:
    - .env
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    networks:
      - vathmos_backend
  phpmyadmin:
    container_name: vathmos_phpmyadmin_container
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: ${MYSQL_HOST}
    depends_on:
      - database
    ports:
      - "8080:80"
    networks:
      - vathmos_backend
networks:
  vathmos_backend: