include:
  - docker-compose.common.yml

version: '3'
services:
  vathmos_backend:
    container_name: vathmos_backend_dev
    image: vathmos_backend
    build:
       context: .
       dockerfile: Dockerfile
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - .:/workspace:cached
      - dev-extensions:/vscode/.vscode-server/extensions
      - dev-node_modules:/workspace/node_modules
    
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
    networks:
      - vathmos_backend

volumes:
  dev-extensions:
    driver: local
  dev-node_modules: