version: "3"
services:
  database:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:8.0.34
    restart: unless-stopped
    environment:
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    networks:
      - vathmos_backend
  phpmyadmin:
    container_name: vathmos_phpmyadmin_container
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: ${MYSQL_CONTAINER_NAME}
    depends_on:
      - database
    ports:
      - "8080:80"
    networks:
      - vathmos_backend
  vathmos_backend:
     build:
       context: .
       dockerfile: Dockerfile
     image: vathmos_backend
     container_name: vathmos_backend
     ports:
       - "${PORT}:${PORT}"
     networks:
       - vathmos_backend
     command: npm run start:dev
     env_file:
       - .env

networks:
  vathmos_backend: